name: linux_container_app
description: "Terminal Linux - Contenedor Linux con Alpine + PROOT + SSH + Networking"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  archive: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
