complete -c chmod -l reference -d 'use RFILE\'s mode instead of MODE values' -r -F
complete -c chmod -l help -d 'Print help information.'
complete -c chmod -s c -l changes -d 'like verbose but report only when a change is made'
complete -c chmod -s f -l quiet -l silent -d 'suppress most error messages'
complete -c chmod -s v -l verbose -d 'output a diagnostic for every file processed'
complete -c chmod -l no-preserve-root -d 'do not treat \'/\' specially (the default)'
complete -c chmod -l preserve-root -d 'fail to operate recursively on \'/\''
complete -c chmod -s R -l recursive -d 'change files and directories recursively'
complete -c chmod -s H -d 'if a command line argument is a symbolic link to a directory, traverse it'
complete -c chmod -s L -d 'traverse every symbolic link to a directory encountered'
complete -c chmod -s P -d 'do not traverse any symbolic links (default)'
complete -c chmod -l dereference -d 'affect the referent of each symbolic link (this is the default), rather than the symbolic link itself'
complete -c chmod -s h -l no-dereference -d 'affect symbolic links instead of any referenced file (useful only on systems that can change the ownership of a symlink)'
complete -c chmod -s V -l version -d 'Print version'
