complete -c df -s B -l block-size -d 'scale sizes by SIZE before printing them; e.g. \'-BM\' prints sizes in units of 1,048,576 bytes' -r
complete -c df -l output -d 'use output format defined by FIELD_LIST, or print all fields if FIELD_LIST is omitted.' -r -f -a "source\t''
fstype\t''
itotal\t''
iused\t''
iavail\t''
ipcent\t''
size\t''
used\t''
avail\t''
pcent\t''
file\t''
target\t''"
complete -c df -s t -l type -d 'limit listing to file systems of type TYPE' -r
complete -c df -s x -l exclude-type -d 'limit listing to file systems not of type TYPE' -r
complete -c df -l help -d 'Print help information.'
complete -c df -s a -l all -d 'include dummy file systems'
complete -c df -l total -d 'produce a grand total'
complete -c df -s h -l human-readable -d 'print sizes in human readable format (e.g., 1K 234M 2G)'
complete -c df -s H -l si -d 'likewise, but use powers of 1000 not 1024'
complete -c df -s i -l inodes -d 'list inode information instead of block usage'
complete -c df -s k -d 'like --block-size=1K'
complete -c df -s l -l local -d 'limit listing to local file systems'
complete -c df -l no-sync -d 'do not invoke sync before getting usage info (default)'
complete -c df -s P -l portability -d 'use the POSIX output format'
complete -c df -l sync -d 'invoke sync before getting usage info (non-windows only)'
complete -c df -s T -l print-type -d 'print file system type'
complete -c df -s V -l version -d 'Print version'
