complete -c readlink -s f -l canonicalize -d 'canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist'
complete -c readlink -s e -l canonicalize-existing -d 'canonicalize by following every symlink in every component of the given name recursively, all components must exist'
complete -c readlink -s m -l canonicalize-missing -d 'canonicalize by following every symlink in every component of the given name recursively, without requirements on components existence'
complete -c readlink -s n -l no-newline -d 'do not output the trailing delimiter'
complete -c readlink -s q -l quiet -d 'suppress most error messages'
complete -c readlink -s s -l silent -d 'suppress most error messages'
complete -c readlink -s v -l verbose -d 'report error message'
complete -c readlink -s z -l zero -d 'separate output with NUL rather than newline'
complete -c readlink -s h -l help -d 'Print help'
complete -c readlink -s V -l version -d 'Print version'
